# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: helloworld.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "gprc_hellowworld.HelloworldRequest" do
    optional :msg, :string, 1
  end
  add_message "gprc_hellowworld.HelloworldResponse" do
    optional :msg, :string, 1
  end
end

module GprcHellowworld
  HelloworldRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("gprc_hellowworld.HelloworldRequest").msgclass
  HelloworldResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("gprc_hellowworld.HelloworldResponse").msgclass
end
