# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: helloworld.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "gprc_helloworld.HelloworldRequest" do
    optional :msg, :string, 1
  end
  add_message "gprc_helloworld.HelloworldResponse" do
    optional :msg, :string, 1
  end
end

module GprcHelloworld
  HelloworldRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("gprc_helloworld.HelloworldRequest").msgclass
  HelloworldResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("gprc_helloworld.HelloworldResponse").msgclass
end
